server.default_listen_address=0.0.0.0

dbms.security.procedures.unrestricted=apoc.*,gds.*,n10s.*
dbms.security.procedures.allowlist=apoc.*,gds.*,n10s.*

dbms.logs.query.enabled=true
dbms.logs.query.threshold=500ms

server.memory.pagecache.size=512M
server.metrics.prometheus.endpoint=0.0.0.0:2004
server.metrics.prometheus.enabled=true
server.metrics.prefix=neo4j
